[project]
name = "system-monitor-mcp"
version = "0.1.0"
description = "A multifunctional MCP server for system monitoring, antivirus scan, mini-games, and usage tracking."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.11.2",
    "psutil>=7.0.0",
]